---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test user
      become: yes
      user:
        name: '{{ item }}'
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr1

  roles:
    - role: ansible_role_pipenv
      pipenv_users:
        - test_usr1
